### ISSUE TITLE
error rate is high in the eval mode

### ISSUE THREAD

**Issue by maxh2018** [cxy1997/LISO#2]
I'm not sure if I didn't understand your code. According to the terminal commands you showed, I got an error rate of up to 49% in validation mode
![图片](https://github.com/cxy1997/LISO/assets/84030620/f108ff51-192a-4e65-bda7-58b80ee0094c)

**Comment by cxy1997** [comment]
Are the pretrained weights successfully loaded? You should see `Loading pretrained weight from ...` in the log if so. 
If you see a line that says `Creating a new model.`, your checkpoint path might be incorrect.
